### ISSUE TITLE
Any updates regard the IMST dongle and openhab ?

### ISSUE THREAD

**Issue by kandersen01** [KuguHome/openhab-binding-wmbus#1]
https://community.openhab.org/t/new-binding-wireless-m-bus-techem-heat-cost-allocators/16974/96?

I really wish there were something I could do to test or try, but I feel abit stuck on this one.

**Comment by mita4kata** [comment]
2020-11-03 22:14:30.117 [WARN ] [binding.wmbus.internal.WMBusReceiver] - Stopped listening for new messages. Reason: {}
java.io.EOFException: null
        at java.io.DataInputStream.readByte(DataInputStream.java:272) ~[?:?]
        at org.openmuc.jmbus.wireless.WMBusConnectionImst$HciMessage.decode(WMBusConnectionImst.java:299) ~[?:?]
        at org.openmuc.jmbus.wireless.WMBusConnectionImst$MessageReceiverImpl.readHciMsg(WMBusConnectionImst.java:75) ~[?:?]
        at org.openmuc.jmbus.wireless.WMBusConnectionImst$MessageReceiverImpl.task(WMBusConnectionImst.java:62) ~[?:?]
        at org.openmuc.jmbus.wireless.WMBusConnectionImst$MessageReceiverImpl.run(WMBusConnectionImst.java:41) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by pokerazor** [comment]
@mita4kata @kandersen01 from our experience, the IMST stick should just work fine? Can you check with the latest version?
