### ISSUE TITLE
please compile for new OH versions

### ISSUE THREAD

**Issue by WiredLife** [KuguHome/openhab-binding-wmbus#3]
the binding has stopped working later OH versions with this error
[ERROR] [ing.wmbus.handler.WMBusBridgeHandler] - Cannot open WMBus device. Connection builder returned: gnu.io.NoSuchPortException
maybe it has something to do with
https://github.com/openhab/openhab-addons/pull/7609/files/dae1dce8d198680b26334d17759ef69ff3c1ef35

can you compile latest version for latest OH?
thank you very much =)

**Comment by MikeTheTux** [comment]
I re-compiled the plugin for OH3. Unfortunatly it's not yet working. `wmbus:wmbusbridge:fb05851252:last_frame` of the bridge populates with cyclic messages, but I do not get an encrypted wmbus device online :-(

**Comment by MikeTheTux** [comment]
Got it working using latest OH3.1.0 SNAPSHOT:

[org.openhab.binding.wmbus-3.1.0-SNAPSHOT_20210305.zip](https://github.com/KuguHome/openhab-binding-wmbus/files/6093423/org.openhab.binding.wmbus-3.1.0-SNAPSHOT_20210305.zip)

You need to configure `include BridgeUID` to `ON`, in order to get it discovery working under OH3:
![grafik](https://user-images.githubusercontent.com/44850211/110174701-caa76580-7e00-11eb-9f7c-39b00fa3a95f.png)

Installation like described in [README.md](https://github.com/KuguHome/openhab-binding-wmbus/blob/master/README.md)

**Comment by WiredLife** [comment]
> Got it working using latest OH3.1.0 SNAPSHOT:
> 
> [org.openhab.binding.wmbus-3.1.0-SNAPSHOT_20210305.zip](https://github.com/KuguHome/openhab-binding-wmbus/files/6093423/org.openhab.binding.wmbus-3.1.0-SNAPSHOT_20210305.zip)
> 
> You need to configure `include BridgeUID` to `ON`, in order to get it discovery working under OH3:
> ![grafik](https://user-images.githubusercontent.com/44850211/110174701-caa76580-7e00-11eb-9f7c-39b00fa3a95f.png)
> 
> Installation like described in [README.md](https://github.com/KuguHome/openhab-binding-wmbus/blob/master/README.md)

Great! 
Which hardware device you use?

**Comment by MikeTheTux** [comment]
> Which hardware device you use?
Amber Wireless

**Comment by MikeTheTux** [comment]
[https://github.com/KuguHome/openhab-binding-wmbus/pull/6](PR 6)

**Comment by pokerazor** [comment]
@WiredLife thanks to the great work of @MikeTheTux , the binding should now work for OH 3. Can you Check?

**Comment by WiredLife** [comment]
dont work with 3.1.0 M4
kills all bindings with serial connection devices

**Comment by MikeTheTux** [comment]
There are some incompatible changes in OH3.1.0 core.
I guess they need to be resolved in order to get the binding running. I can have a look once I updated to OH3.1.0.

**Comment by Baggerfahrer** [comment]
is this issue related to [https://community.openhab.org/t/serial-binding-error-during-instantiation-of-the-implementation-object/122931](url)?

for me, the binding dont work either, the serial binding does not show up (stays uninitialized).

any hints?

**Comment by JensHoRi** [comment]
I just tried to get WM-Bus-Binding to work after Stick arrived.

While starting the binding, console shows following error:

```
openhab> bundle:start 281
Error executing command: Error executing command on bundles:
Error starting bundle 281: Could not resolve module: org.openhab.binding.wmbus [281]
Unresolved requirement: Import-Package: javax.measure; version="[1.0.0,2.0.0)"
```

While searching in openhab community, saw this sometimes caused by missing dependencies in pom.xml?

Tried with your linked build from March

**Comment by MikeTheTux** [comment]
Please give the latest version [org.openhab.binding.wmbus-3.1.0-SNAPSHOT-20210805.zip](https://github.com/KuguHome/openhab-binding-wmbus/files/7364608/org.openhab.binding.wmbus-3.1.0-SNAPSHOT-20210805.zip) from PR https://github.com/KuguHome/openhab-binding-wmbus/pull/7 a try.

**Comment by JensHoRi** [comment]
Installation with this SNAPSHOT worked.

Stick up and running. Thanks for very fast reply! Didn't saw that new SNAPSHOT before, sorry for asking.

Just one information: After restart of openhab Device-Status of stick is "unknown" until I stop it in UI and start Thing again.

Log shows following error:

```
2021-10-18 15:19:02.208 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.NullPointerException: null
        at org.openmuc.jrxtx.JRxTxPort.openSerialPort(JRxTxPort.java:61) ~[?:?]
        at org.openmuc.jrxtx.SerialPortBuilder.build(SerialPortBuilder.java:140) ~[?:?]
        at org.openmuc.jmbus.transportlayer.SerialLayer.open(SerialLayer.java:30) ~[?:?]
        at org.openmuc.jmbus.wireless.AbstractWMBusConnection.open(AbstractWMBusConnection.java:77) ~[?:?]
        at org.openmuc.jmbus.wireless.WMBusConnection$Builder.build(WMBusConnection.java:162) ~[?:?]
        at org.openmuc.jmbus.wireless.WMBusConnection$WMBusSerialBuilder.build(WMBusConnection.java:98) ~[?:?]
        at org.openhab.binding.wmbus.handler.WMBusBridgeHandler.lambda$0(WMBusBridgeHandler.java:135) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```
I'll wait now until Devices got discovered, hope it will work. Need to start with read out some "heat cost allocators"

Many thanks for your work on this binding for openhab. Would be much appreciate if it will be part of official distribution OH 3.2 :-)

**Comment by JensHoRi** [comment]
Is there a chance to get a 3.2.0 jar too?

**Comment by t2000** [comment]
@KuguHome: Do you have any plans in adding this binding to the official Oh distribution?

I think about starting to play around with my Sensus iPERL water meter which uses this protocol and together with the open PR about CUL devices, your binding looks promissing.
